version: "3"
services:
  zlmedia-server:
    image: zlmediakit/zlmediakit:master
    ports:
      - "1935:1935"
      - "8554:554"
      - "8080:80"
      - "8443:443"
      - "10000:10000"
      - "8000:8000/udp"
      - "9000:9000/udp"
      - "10000:10000/udp"
    # command:
    #   - bash
    #   - -c 
    #   - "sleep infinity"
    restart: always
    volumes:
      - .:/app