version: "3"
services:
  zlm-server-12345:
    image: zlmediakit/zlmediakit:master
    ports:
      - "1935:1935"
      - "8554:554"
      - "8080:80"
      - "8443:443"
      - "10000:10000"
      - "8000:8000/udp"
      - "9000:9000/udp"
      - "10000:10000/udp"
    # command:
    #   - bash
    #   - -c 
    #   - "sleep infinity"
    restart: always
    volumes:
      - ./conf:/opt/media/conf
    networks:
      - bridge-net

  zlm-server-67890:
    image: zlmediakit/zlmediakit:master
    ports:
      - "1934:1935"
      - "8553:554"
      - "8079:80"
      - "8442:443"
      - "9999:10000"
      - "7999:8000/udp"
      - "8999:9000/udp"
      - "9999:10000/udp"
    # command:
    #   - bash
    #   - -c 
    #   - "sleep infinity"
    restart: always
    volumes:
      - ./conf:/opt/media/conf
    networks:
      - bridge-net
networks:
  bridge-net:
    external:
      name: cctv-hub